[profile.default]
src = 'src'
out = 'out'
test = 'test'
libs = ['lib']
solc = "0.8.18"
fs_permissions = [
    { access = "read", path = "./broadcast"},
    { access = "read", path = "testdata/blockhashmerkleleaves"},
    { access = "read", path = "testdata/blockheaderinfo"},
]
gas_reports = ["*"]

[fuzz]
runs = 1000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
